language: node_js
node_js: "12"
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.npm
script: 
  - npm run build
  - npm test
# services:
#   - mysql
# before_install:
#   - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
